ELASTICSEARCH_HOST="https://my-deployment-3eafc9.es.ap-south-1.aws.elastic-cloud.com:9243"
ELASTICSEARCH_USERNAME="elastic"
ELASTICSEARCH_PASSWORD="NuwRaaWUktq5FM1QJZe6iexV"
OPENAI_API_KEY="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"
